import { create } from 'zustand';
import { createEntitySlice } from './entitySlice';

const useStore = create((set) => ({
  // Current project
  currentProject: null,
  setCurrentProject: (project) => set({ currentProject: project }),

  // Sources (PDFs/documents in tabs)
  sources: [],
  activeSourceId: null,
  setSources: (sources) => set({ sources }),
  addSource: (source) =>
    set((state) => ({
      sources: [...state.sources, source],
      activeSourceId: source.id,
    })),
  removeSource: (id) =>
    set((state) => ({
      sources: state.sources.filter((s) => s.id !== id),
      activeSourceId: state.activeSourceId === id ? null : state.activeSourceId,
    })),
  setActiveSource: (id) => set({ activeSourceId: id }),

  // PDF viewer state
  currentPage: 1,
  pdfScale: 1.2,
  setCurrentPage: (page) => set({ currentPage: page }),
  setScale: (scale) => set({ pdfScale: scale }),

  // Annotation tool
  activeTool: 'select', // 'select', 'highlight', 'ink', 'text'
  setActiveTool: (tool) => set({ activeTool: tool }),

  // Annotations for current source
  annotations: [],
  setAnnotations: (annotations) => set({ annotations }),
  addAnnotation: (annotation) =>
    set((state) => ({
      annotations: [...state.annotations, annotation],
    })),

  // Map state (deprecated - kept for backward compatibility)
  mapView: 'map', // 'map' or 'source'
  setMapView: (view) => set({ mapView: view }),

  // Dynamic Tabs
  tabs: [
    {
      id: 'default-map',
      type: 'map',
      title: 'Map',
      data: null,
      isDirty: false,
    },
  ],
  activeTabId: 'default-map',
  addTab: (tab) =>
    set((state) => {
      const newTab = {
        id: tab.id || `tab-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        type: tab.type,
        title: tab.title,
        data: tab.data || null,
        isDirty: false,
      };
      return {
        tabs: [...state.tabs, newTab],
        activeTabId: newTab.id,
      };
    }),
  removeTab: (tabId) =>
    set((state) => {
      // Don't allow removing the last tab
      if (state.tabs.length <= 1) return state;

      const newTabs = state.tabs.filter((t) => t.id !== tabId);
      let newActiveTabId = state.activeTabId;

      // If we're removing the active tab, switch to the previous tab
      if (state.activeTabId === tabId) {
        const removedIndex = state.tabs.findIndex((t) => t.id === tabId);
        const newIndex = Math.max(0, removedIndex - 1);
        newActiveTabId = newTabs[newIndex].id;
      }

      return {
        tabs: newTabs,
        activeTabId: newActiveTabId,
      };
    }),
  setActiveTab: (tabId) =>
    set((state) => {
      const tab = state.tabs.find((t) => t.id === tabId);
      // If switching to a PDF tab, also update activeSourceId
      const updates = { activeTabId: tabId };
      if (tab?.type === 'pdf' && tab.data?.source?.id) {
        updates.activeSourceId = tab.data.source.id;
      }
      return updates;
    }),
  updateTab: (tabId, updates) =>
    set((state) => ({
      tabs: state.tabs.map((t) => (t.id === tabId ? { ...t, ...updates } : t)),
    })),

  // Places (pins) - generated by entitySlice factory
  ...createEntitySlice('place')(set),

  // Selected annotation (for linking to map)
  selectedAnnotationId: null,
  setSelectedAnnotation: (id) => set({ selectedAnnotationId: id }),

  // Annotation modal
  annotationModalOpen: false,
  pendingAnnotation: null,
  openAnnotationModal: (annotation) =>
    set({
      annotationModalOpen: true,
      pendingAnnotation: annotation,
    }),
  closeAnnotationModal: () =>
    set({
      annotationModalOpen: false,
      pendingAnnotation: null,
    }),

  // Advanced search modal
  advancedSearchModalOpen: false,
  openAdvancedSearch: () => set({ advancedSearchModalOpen: true }),
  closeAdvancedSearch: () => set({ advancedSearchModalOpen: false }),

  // Pin placement mode (for linking annotations to map)
  pinPlacementMode: false,
  pendingPinAnnotationId: null,
  startPinPlacement: (annotationId) =>
    set({
      pinPlacementMode: true,
      pendingPinAnnotationId: annotationId,
      mapView: 'map', // Switch to map view
    }),
  cancelPinPlacement: () =>
    set({
      pinPlacementMode: false,
      pendingPinAnnotationId: null,
    }),

  // Location placement mode (for setting entity coordinates)
  locationPlacementMode: false,
  pendingLocationEntity: null, // { entityId, entityType, entityName }
  startLocationPlacement: (entityId, entityType, entityName) =>
    set({
      locationPlacementMode: true,
      pendingLocationEntity: { entityId, entityType, entityName },
    }),
  cancelLocationPlacement: () =>
    set({
      locationPlacementMode: false,
      pendingLocationEntity: null,
    }),

  // Artifacts - generated by entitySlice factory
  ...createEntitySlice('artifact')(set),
  selectedArtifact: null,
  setSelectedArtifact: (artifact) => set({ selectedArtifact: artifact }),

  // Map overlays
  mapOverlays: [],
  setMapOverlays: (overlays) => set({ mapOverlays: overlays }),
  addMapOverlay: (overlay) =>
    set((state) => ({
      mapOverlays: [...state.mapOverlays, overlay],
    })),

  // Overlay georeferencing mode
  overlayMode: false,
  openOverlayMode: () => set({ overlayMode: true }),
  closeOverlayMode: () => set({ overlayMode: false }),
  onOverlayMapClick: null,

  // People (knowledge graph entities) - generated by entitySlice factory
  ...createEntitySlice('person', 'people')(set),

  // Events (knowledge graph entities) - generated by entitySlice factory
  ...createEntitySlice('event')(set),

  // Theories (knowledge graph entities) - generated by entitySlice factory
  ...createEntitySlice('theory', 'theories')(set),

  // Entity Pages (hybrid storage: metadata in DB, content in Storage)
  entityPages: [], // Array of entity page metadata
  setEntityPages: (pages) => set({ entityPages: pages }),
  addEntityPage: (page) =>
    set((state) => ({
      entityPages: [...state.entityPages, page],
    })),
  updateEntityPageInStore: (entityId, updates) =>
    set((state) => ({
      entityPages: state.entityPages.map((p) =>
        p.entity_id === entityId ? { ...p, ...updates } : p
      ),
    })),
  removeEntityPage: (entityId) =>
    set((state) => ({
      entityPages: state.entityPages.filter((p) => p.entity_id !== entityId),
    })),

  // Entity Links (for network graph)
  entityLinks: [],
  setEntityLinks: (links) => set({ entityLinks: links }),
  addEntityLink: (link) =>
    set((state) => ({
      entityLinks: [...state.entityLinks, link],
    })),
  removeEntityLink: (linkId) =>
    set((state) => ({
      entityLinks: state.entityLinks.filter((l) => l.id !== linkId),
    })),

  // Reset project-specific state (called when switching projects)
  resetProjectState: () =>
    set({
      sources: [],
      activeSourceId: null,
      annotations: [],
      tabs: [
        {
          id: 'default-map',
          type: 'map',
          title: 'Map',
          data: null,
          isDirty: false,
        },
      ],
      activeTabId: 'default-map',
      places: [],
      artifacts: [],
      selectedArtifact: null,
      mapOverlays: [],
      people: [],
      events: [],
      theories: [],
      entityPages: [],
      entityLinks: [],
      currentPage: 1,
      selectedAnnotationId: null,
      pinPlacementMode: false,
      pendingPinAnnotationId: null,
      locationPlacementMode: false,
      pendingLocationEntity: null,
    }),
}));

export default useStore;
