-- Disable Row Level Security for Arcanum (solo research tool)
-- Run this in Supabase SQL Editor

ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE annotations DISABLE ROW LEVEL SECURITY;
ALTER TABLE places DISABLE ROW LEVEL SECURITY;
ALTER TABLE annotation_place_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE map_overlays DISABLE ROW LEVEL SECURITY;
ALTER TABLE artifacts DISABLE ROW LEVEL SECURITY;
